server:
  port: 8080
spring:
  application:
    name: "ms-user"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

security:
  jwt:
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7

adapters:
  postgresql:
    host: localhost
    port: 5432
    database: ms_user
    schema: public
    username: postgres
    password: postgres
